### ISSUE TITLE
Feature Request: Charge indicator

### ISSUE THREAD

**Issue by TheGroundZero** [ngocjohn/vehicle-info-card#1]
While it's possible to add this manually e.g., by creating my own vehicle status card, it would be nice to have a built-in Charge indicator for EVs.

I'm thinking of an indiciation of the car being charged, maybe also including charge power and charge target.
E.g., `Charging (60/80%)` for when the battery currently is 60% full and the target is set to 80%

Maybe an additional icon in the top bar?
![image](https://github.com/ngocjohn/vehicle-info-card/assets/2406013/6a42a5d8-e6af-4b74-a7bc-2e96f8a60cf5)

**Comment by ngocjohn** [comment]
Hi, it's certainly possible as another option to add optional indicators, I'll try to figure out how to combine it in the next update. 😄

**Comment by TheGroundZero** [comment]
Good looking 👍
![image](https://github.com/ngocjohn/vehicle-info-card/assets/2406013/823bf290-3c1d-433b-9015-032f0e58710a)

Curious to see how it looks while charging

**Comment by ngocjohn** [comment]
Hi, the bar only shows the current battery level and range.  I don't have an EV, so I have no way of knowing what other sensors are available for these cars and what they show. For now I'll just leave these basic indicators.

**Comment by TheGroundZero** [comment]
The MBAPI integration exposes e.g. `sensor.[car]_charging_power` giving you the charge power in kW, and `sensor.[car]_range_electric` has an attribute `chargingactive: true/false`.
The Range Electric entity (and some other entities as well) also exposes the charging program through the attribute `selectedChargeProgram: "0/1/2/3"`. They're strings and `"0"` corresponds with Standard , `"2"` with Home, and `"3"` with Work

**Comment by ngocjohn** [comment]
> the charging program through the attribute `selectedChargeProgram: "0/1/2/3"`. They're strings and `"0"` corresponds with Standard , `"2"` with Home, and `"3"` with Work


@TheGroundZero  Hi! There are 4 programs, you only listed 3 of them, which program is missing? I made a rough template for the charge status, it only shows when the charge status is active. Clicking on it will show more data. What do you think? 

![charge-status2](https://github.com/ngocjohn/vehicle-info-card/assets/96962827/e357187f-11a8-4ada-9b97-a9418d9a25d6)

**Comment by TheGroundZero** [comment]
> > the charging program through the attribute `selectedChargeProgram: "0/1/2/3"`. They're strings and `"0"` corresponds with Standard , `"2"` with Home, and `"3"` with Work
> 
> @TheGroundZero Hi! There are 4 programs, you only listed 3 of them, which program is missing?
No clue. MBAPI only seems to report 0-2-3. See also https://community.home-assistant.io/t/mercedes-me-component/41911/1744

> I made a rough template for the charge status, it only shows when the charge status is active. Clicking on it will show more data. What do you think?
That looks awesome!

**Comment by ngocjohn** [comment]
Oh, are you in the forum too? Could you send me your nick, I'd send you an updated version with that feature added for testing. If it would be possible, since I don't have the necessary sensors, I have no chance to test it. Thank you in advance


![CleanShot 2024-06-11 at 16 15 59](https://github.com/ngocjohn/vehicle-info-card/assets/96962827/6a5d237f-40fd-49b9-8c3b-660f4c681c5e)

**Comment by ngocjohn** [comment]
added in v1.0.3 😄
