### ISSUE TITLE
Rounding issue on charging power 

### ISSUE THREAD

**Issue by elRadix** [ngocjohn/vehicle-info-card#12]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

round to 2 decimal 

**Describe alternatives you've considered**

**Additional context**
![Screenshot_20240617_122305_Home Assistant](https://github.com/ngocjohn/vehicle-info-card/assets/6258894/35ed78fd-6659-4542-885b-74d34bdba624)

**Comment by ngocjohn** [comment]
Thanks for the warning, I'll fix it in the next update.  😄
