### ISSUE TITLE
Feature Request: Adblue Level

### ISSUE THREAD

**Issue by Jealy91** [ngocjohn/vehicle-info-card#13]
Hi, would it be possible to display the current level of the adblue tank somewhere on the card?

It's returned from the integration in percentage as tankLevelAdBlue attribute of the fuel_level entity.

Thanks, love the card!

P.S - would be awesome if the card had the option to lock/unlock the car and move the windows using the service calls in the integration, but I feel it may be beyond the scope of the card.

**Comment by ngocjohn** [comment]
Hi there, of course it is possible to add more items to the status. I will add to the trip card in the overview.  Could you send me the attribute name for the adblue level? I'm working on improving the tire pressures tab now, it seems too simple. I'll add it to the next release.. 

I have also thought about these features for vehicle control, but I don't have subscriptions for these services nor do I have these services available for my vehicles. I only have simple lock control, so I can't even simulate these service calls.  I need someone to test it. 😮‍💨   

![CleanShot 2024-06-28 at 14 44 13@2x](https://github.com/ngocjohn/vehicle-info-card/assets/96962827/ff4d128f-a702-4fb4-a13f-d397fcfa4b6b)

**Comment by ngocjohn** [comment]
Oh, I had a sensor for adblue level all along, I just somehow forgot to include it in the entries. 🤦  Can you, please confirm if you have the sensor.car_adblue_level or as an attribute?

**Comment by Jealy91** [comment]
Hey, thanks for looking into it!

I do indeed have the sensor.car_adblue_level!

I didn't include it in my post as I had previously made my own template entity using:
`"{{ state_attr('sensor.car_fuel_level','tankLevelAdBlue') }}"`
Which has made my "official" one suffix with _2, but I can sort that.

But I remember that it's now provided by the integration.
(And I can remove that template entity!)

**Comment by ngocjohn** [comment]
That's great, as soon as I have a version ready I'll get back to you with a functional test. And about the sensor, you can rename it as you want. The entities are generated from the device id integration and it has a VIN prefix, so you can have as many cars as you want, the entity is unique.

**Comment by ngocjohn** [comment]
@Jealy91 I had some time off and made some progress for remote control. I didn't want to add a new button, so I was looking for a solution where it would be best to place the trigger for this new card. So I added it as a new indicator that can be hidden via config. All services commands from integration will be available, with vin/fin added automatically to the command. 

These individual control buttons can be selected via the UI editor, each user chooses which function he wants to display or which one is available for his car. Here is a preview for the new feat. Give me some feedback... thanks 😄 

https://github.com/ngocjohn/vehicle-info-card/assets/96962827/49d8374e-9d2a-4090-b1b7-3450829e1461

**Comment by Jealy91** [comment]
Looks great. Better than anything I could have imagined for sure!

Nice work!

**Comment by Jealy91** [comment]
Updated & tested, AdBlue showing & the services work a treat.

Thanks a lot @ngocjohn! Great work!
