### ISSUE TITLE
Missing rows

### ISSUE THREAD

**Issue by TheGroundZero** [ngocjohn/vehicle-info-card#2]
Looks like I'm missing the text for some sensors in my Vehicle Status card.

![image](https://github.com/ngocjohn/vehicle-info-card/assets/2406013/7994734d-410d-4d4c-acef-5990207c5299)

Looks like I'm missing Low Coolant and Engine Light warnings.
![image](https://github.com/ngocjohn/vehicle-info-card/assets/2406013/2c75d791-a082-404a-97e4-0d01d53e2bbc)

Those are indeed not available to me in Home Assistant. So maybe an issue for @ReneNulschDE instead?
![image](https://github.com/ngocjohn/vehicle-info-card/assets/2406013/65427b79-e811-4ae2-99ee-d401ee9f561d)

**Comment by ReneNulschDE** [comment]
When the sensors are not created that normally the API has not delivered any data. You can send me your diagnostic download to mbdev.ngocjohn.i2@nulsch.de... and i will check it.
