### ISSUE TITLE
How to associate a sub card with a button

### ISSUE THREAD

**Issue by bradkemper** [ngocjohn/vehicle-info-card#46]
There is an example of using an entities card for the Vehicle status button. But how do you tell it that the card you created is the one to substitute for what you normally see when you press that button? Is it just by matching the card title to the exact words of the button?

**Comment by bradkemper** [comment]
It would be great if we could add any button there and associate it with any card.

**Comment by ngocjohn** [comment]
Hi @bradkemper ! The basic inspiration for the card comes from the ME app. I’ve chosen 4 buttons that I think best represent the main vehicle status. I’ve set up these buttons for the card accordingly.

If you’d like to customize individual sub-cards, you can easily do that using the YAML editor and adding any Lovelace code you like.

The simplest approach is to create a new card the usual way, then just copy the code over to your specific card as needed. Hope this helps!

![CleanShot2024-08-24at21 01 24-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/6bb91cea-5bd1-40db-8311-db51d1252c4d)

About the possibility of cutomization of buttons, I will try to add this function as well 😄

**Comment by ngocjohn** [comment]
New options for customizing buttons and sub card added. You can try it now in the pre-release or in the new release soon. 
![CleanShot 2024-08-25 at 08 31 59@2x](https://github.com/user-attachments/assets/770efe81-7290-4910-8da1-6acf38666328)

**Comment by bradkemper** [comment]
Nice!
