### ISSUE TITLE
Allow changing of subcard titles

### ISSUE THREAD

**Issue by bradkemper** [ngocjohn/vehicle-info-card#47]
### Short summary

“Tyres” is very British. I want to change it to “Tires”

### Detailed description

Part 1: use language localization, so it will automatically chose “Tires” instead of “Tires” for me here in the US. Or use German if it detects that my phone is using German. 

Part 2: make the subcard fields editable. 

### Additional context 🗒️

“Tyres” is just never the spelling used in the US.

**Comment by bradkemper** [comment]
By the way, the YAML has `selected_language: en`, not `en_GB`

**Comment by ngocjohn** [comment]
I am aware of this bug, the fix is ready and will be in the next release. 👍

**Comment by jrb80** [comment]
How do I restore "tyres"? Do I need to insert a YAML line to customise (not customize) the title?
