### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ciring** [ngocjohn/vehicle-info-card#56]
### Short summary 📝

"doors" status display error

### Detailed description 📋

"doors" status should be “closed”，and "sunroof" status is normal，should be white

### Version 📌

v1.3.0

### Environment 🌐

docker Home Assistant core 2024.9.1。Region china

### Logs and screenshots 📂

![image](https://github.com/user-attachments/assets/b686afd8-3824-4ba1-9db2-155eb09d21aa)
![image](https://github.com/user-attachments/assets/65d3dd74-192b-445f-9f2a-5a96a5fd1f2a)

**Comment by ngocjohn** [comment]
Hey @ciring , I'll look into it. I'm thinking of adding the sunroof as a sensor itself and not as an attribute from sensor._lock. Do you have sensor._sunroof_status in the component? And what is its state?

**Comment by ciring** [comment]
> Hey @ciring , I'll look into it. I'm thinking of adding the sunroof as a sensor itself and not as an attribute from sensor._lock. Do you have sensor._sunroof_status in the component? And what is its state?

![image](https://github.com/user-attachments/assets/e2bcc6c9-7a7e-440b-9729-51cf95b9edc2)
![image](https://github.com/user-attachments/assets/8b77c31c-f235-4c18-a7b5-4e465a4fc80f)

yes，its name is sensor.VIN_sunroof_status, and its status is closed，the same as in sensor.VIN_lock

**Comment by ngocjohn** [comment]
Fixed, there was a conflict with the new added sensor charge flap for EV.  Moved sunroof status under windows. It makes more sense.. 
![CleanShot 2024-09-09 at 08 20 29](https://github.com/user-attachments/assets/302d450a-87b8-4038-87cc-c07f71bd1d64)
