### ISSUE TITLE
Cant open submenus

### ISSUE THREAD

**Issue by weto91** [ngocjohn/vehicle-info-card#58]
Submenu buttons cant be opened.

**Comment by ngocjohn** [comment]
Can you describe the issue more?

**Comment by weto91** [comment]
> Can you describe the issue more? 

Yes, I have this card installed along with the latest version of Mercedes Me in Home Assistant. The card can be seen on its main screen, but if I press any of the buttons (trip data, echo, tire pressure... etc) it does nothing. does not open the corresponding menus. It was working for me until a couple of weeks ago when an update from Mercedes Me appeared.

**Comment by weto91** [comment]
https://github.com/user-attachments/assets/6efb5f6c-1d7c-4fbe-90c1-34ad2625081a

**Comment by weto91** [comment]
> https://github.com/user-attachments/assets/6efb5f6c-1d7c-4fbe-90c1-34ad2625081a

As you can see in the video, im pushing the buttons, but nothing happened...

**Comment by weto91** [comment]
More info:
 downgrading the js to 1.1.2 works perfectly, the problem starts on 1.2.0 version.

**Comment by ngocjohn** [comment]
Do you have any custom card or custom button? Try to create a brand new card with default settings. And update to the latest version.

**Comment by betimo** [comment]
Same issue.

**Comment by ngocjohn** [comment]
I'm working on a fix 👍
