### ISSUE TITLE
[Bug] Mini location map no longer loads

### ISSUE THREAD

**Issue by ufozone** [ngocjohn/vehicle-info-card#59]
### Short summary 📝

Mini location map no longer loads

### Detailed description 📋

Since the update from v1.2.0 to 1.3.0, the map no longer loads in the card. 

Map request up to v1.2.0:
https://api.mapbox.com/styles/v1/emkay2k9/clyd2zi0o00mu01pgfm6f6cie/tiles/15/17325/11009@2x?access_token=pk.eyJ1IjoiZW1rYXkyazkiLCJhIjoiY2xrcHo5NzJwMXJ3MDNlbzM1bWJhcGx6eiJ9.kyNZp2l02lfkNlD2svnDsg

Map request since v1.3.0:
https://api.mapbox.com/styles/v1/emkay2k9/clyd2zi0o00mu01pgfm6f6cie/tiles/15/17325/11009@2x?access_token=undefined

The `access_token` is missing and I have not found a YAML configuration option to pass it.

The mapbox URL is assembled here:
https://github.com/ngocjohn/vehicle-info-card/blob/7b9c684d969480641eb0f8250178c7f2fa7d8c33/src/components/map-card.ts#L217

`process.env.MAPBOX_API` no longer seems to exist:
https://github.com/ngocjohn/vehicle-info-card/blob/7b9c684d969480641eb0f8250178c7f2fa7d8c33/src/components/map-card.ts#L216

There was no change in these two areas. I'm not familiar with the programming language (I honestly don't even know what it is), and unfortunately I can't debug any deeper. :-(

### Version 📌

v1.3.0

### Environment 🌐

In all browsers

**Comment by ngocjohn** [comment]
Hi, please download version 1.3.1 again if you already have it. If not, update to the new one. I've updated the map API. 👍

**Comment by ufozone** [comment]
Hi @ngocjohn , thank you for your very quick answer! Mhhh, same problem with a freshly downloaded v1.3.1 and completely deleted browser cache.

**Comment by ngocjohn** [comment]
I have uploaded the new file directly into the release again now 😄  If you downloaded via HACS, try redownloading the latest version and hard refresh the browser. 

![CleanShot 2024-09-11 at 23 11 25@2x](https://github.com/user-attachments/assets/52c9e573-cadc-48d0-93a0-7ec8f206faf1)

**Comment by ufozone** [comment]
Re-downloading from Hacs did not work. Hard download from the releases, re-upload to the frontend folder of HA and hard restart of HA worked. 👍

Thank you so much for this great card!

Is there actually an option to display the pictures of own car for the tire pressure card? 😉

**Comment by ngocjohn** [comment]
All square images should work. I'll add the possibility to upload a custom image as background.. 😉

**Comment by betimo** [comment]
Resetting frontend cache worked for me.

**Comment by ngocjohn** [comment]
> Is there actually an option to display the pictures of own car for the tire pressure card?

Hi, @ufozone Yes... Coming soon in a new release.. 🎉 

![custom-tire-bg](https://github.com/user-attachments/assets/3aa969f1-6974-420e-bb7f-efd675a7e82d)

**Comment by ufozone** [comment]
@ngocjohn , very nice!
