### ISSUE TITLE
[Bug] Entity dropdown says "No matching entites found"

### ISSUE THREAD

**Issue by Hooshee** [ngocjohn/vehicle-info-card#84]
### Short summary 📝

When I try to create the card from gui, the entity selector cannot find matching entity

### Detailed description 📋

When I try to create the card from gui, the entity selector cannot find matching entity. But in the code editor when I put there "sensor.car", it finds my vehicle

### Version 📌

1.5.0

### Environment 🌐

Firefox Windows 11, latest HA. 

### Logs and screenshots 📂

![image](https://github.com/user-attachments/assets/126f5a6e-ae84-4d1f-92f8-fa3a0ddd5356)
![image](https://github.com/user-attachments/assets/c5be7a56-9a2c-4c45-b5a9-14d1089c52e4)

**Comment by ngocjohn** [comment]
Hi @Hooshee, entity is already automatically selected, otherwise you would not have the data displayed in the buttons. Entity is default in the form sensor.***_car where *** is car license plate

**Comment by ngocjohn** [comment]
I probably know where the mistake is. I assumed that the user would have entities in the default form, so I filtered out the sensor.***_car entity and you only have the entity as sensor.car 😄 I will modify this method and publish in a new release 👍

**Comment by ngocjohn** [comment]
@Hooshee Or ideally in the integration of the device, which is the car and name it. You would then have a better overview... 
![CleanShot 2024-11-25 at 15 06 36@2x](https://github.com/user-attachments/assets/620c5bcb-63b1-49b8-a4bf-975912421b92)

**Comment by Hooshee** [comment]
Will do, actually if I enter it in the yaml, and go back to gui, it deletes the yaml row of entity... so I'll rename my entity id.

**Comment by Hooshee** [comment]
WEll, I still can't manage to make it work. It actually was named as per you suggested: 

![image](https://github.com/user-attachments/assets/8d1b182b-d4ac-404b-9676-0de033b3399d)

I renamed sensor.car to sensor.tfh300 and other versions, but it still does not show up in the entity list.

**Comment by ngocjohn** [comment]
That's strange, what is the entity for the sensor car? You can rename the entity_id for sensor car .. sensor.something_car

**Comment by ngocjohn** [comment]
Entity list in the editor are just filtered entities start with sensor. and end with _car .. If you have it in another form, it won't be there.

**Comment by Hooshee** [comment]
I see... however, I cannot rename the sensor.car to anything else then sensor.xxxxxxx. The sensor part is not changeable.

**Comment by Hooshee** [comment]
It works! I misunderstood the format, but now it's OK. Thank you very much!
