### ISSUE TITLE
[Bug] <Integration ngocjohn/vehicle-info-card> Repository structure for v1.6.0 is not compliant

### ISSUE THREAD

**Issue by CDM040971** [ngocjohn/vehicle-info-card#91]
### Short summary 📝

Issue Loading Repo V1.6.0 Not Compliant 

### Detailed description 📋

When following the Repo install guide I receive this message "<Integration ngocjohn/vehicle-info-card> Repository structure for v1.6.0 is not compliant"

### Version 📌

V.1.6.0

### Logs and screenshots 📂

![image](https://github.com/user-attachments/assets/ef8507af-fe01-43e7-b8ec-7c0b41c4df27)

**Comment by ngocjohn** [comment]
Hi @CDM040971, choose type Dashboard

**Comment by CDM040971** [comment]
That worked thank you so much :)

**Comment by CDM040971** [comment]
Works perfectly when you know how :) ~ Thank you John
