### ISSUE TITLE
[Feature] Change color of button-action-tripCards, etc.

### ISSUE THREAD

**Issue by wookash** [ngocjohn/vehicle-info-card#96]
### Short summary

Change color of button-action-tripCards background, etc. using card_mod

### Detailed description

Hi, 

First of all - amazing card, thank you!

Secondly, it's not really a feature, but I've tried customising your card with card_mod. I was able to change the color of the card - background (using ha_card, see below), but cannot find the right way to address the button-action-tripCards and the other buttons.. could you help me? How do I address this button and where do I need to style it (at the level of the card or where the buttons are defined?). Even if you help me find the correct name it will be enough, I can work my way from there.

`card_mod:
  style: |
    ha-card {
      background: rgba(25, 25, 25, 0.4) !important;
    }
`

Thanks in advance!

**Comment by ngocjohn** [comment]
Hi @wookash , with the card mod you can modify the elements gradually via shadow-root in this way. 
```
card_mod:
  style:
    .: |
      ha-card {
        background-color: green !important;
      }
    vehicle-buttons $: |
      .grid-item {
        background-color: blue !important;
      }
```
the important thing is this
```
.: | 
```
![CleanShot 2024-12-15 at 23 24 20](https://github.com/user-attachments/assets/9e9f9b9a-1882-4ba3-b1f9-c08810fc3e98)

**Comment by wookash** [comment]
Awesome, thanks for a prompt reply. Works like a charm! I appreciate the resources - I was actually looking for something like card mod helper from your second link. Re the first link - I did not know what to look for earlier, and I’ve just learned one more thing. All the best
